# Site settings
title: mobyvb
email: mobyvb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Maximillian Mohammed von Briesen
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mobyvb.com" # the base hostname & protocol for your site
twitter_username: mobyvb
github_username:  mobyvb

# Build settings
markdown: kramdown
